<?php
session_start(); // Starting sessions is required for CAPTCHA
if ($_SESSION["code"] == $_POST["captcha"]) { // Check if code generated by captcha.php is the same as the one entered by an user.
  $connection = mysql_connect("localhost", "nkalok", "HSPiR!UH8klgODjzQB3="); // Establishing Connection with Server..
  $db = mysql_select_db("regformdb", $connection); // Selecting Database. "regformdb" corresponds to name of the database.
  //Fetching Values from URL
  $name2=$_POST['name1'];
  $surname2=$_POST['surname1'];
  $am2=$_POST['am1'];
  $exam2=$_POST['exam1'];
  $repeatLab2=$_POST['repeatLab1'];
  $email2=$_POST['email1'];
  $priority_1_2=$_POST['priority_1_1'];
  $priority_2_2=$_POST['priority_2_1'];
  $priority_3_2=$_POST['priority_3_1'];
  $priority_4_2=$_POST['priority_4_1'];
  $priority_5_2=$_POST['priority_5_1'];

  /*Insert query.
    === NOTES: ===
    - "students" corresponds to the name of the table in the database.
    - "name, surname, am etc." correspond to row names of the table.
    - "$name, '$surname2', '$am2' etc." corresponds to values being inserted into the rows.
    === END OF NOTES ===
    */
  $query = mysql_query("insert into students(name, surname, am, exam, repeat_lab, email, priority_1, priority_2, priority_3, priority_4, priority_5) values ('$name2', '$surname2', '$am2','$exam2','$repeatLab2','$email2','$priority_1_2','$priority_2_2','$priority_3_2','$priority_4_2','$priority_5_2')");
  mysql_close($connection); // Close the connection
  $to  = $email2;
  $subject = 'Registration completed successfully!';

  // To send HTML mail, the Content-type header must be set
  $headers  = 'MIME-Version: 1.0' . "\r\n";
  $headers .= 'Content-type: text/html; charset=utf-8' . "\r\n";

  // Put your HTML here
  //$message = '<html><body>hello world</body></html>';
  $message = file_get_contents('basic.html');
  // Mail it
  mail($to, $subject, $message, $headers);
  echo "Η εγγραφή ολοκληρώθηκε επιτυχως!"; //Submission succesfull. Display message.
}  else {
      die("Η εγγραφή δεν ολοκληρώθηκε.Παρακαλώ ελέγξτε τη φόρμα για σφάλματα και προσπαθήστε ξανά. Αν το πρόβλημα επιμένει , παρακαλώ απευθυνθείτε στον υπεύθυνο καθηγητή."); //Submission Failed. Display message.
  }
?>
